# -*- coding: utf-8 -*-
"""1_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/192p2hCgEzDY5axGLLqT6n0GJelp7oNbN
"""

# 1.
F = input("Insert the F degrees for convertion to C degrees: ")

def c_degrees(f0): 
  return (5/9)*(float(f0) - 32)

def after(f2):
  n2= []
  n3 = []
  b = False
  for i in f2:
    if i == ".":
      b = True
    if b == True:
      n2.append(i)
  for i in n2:
    if i != ".":
      n3.append(i)
  return len(n3)

for i in F:
  if i ==".":
    print(round(c_degrees(F),after(F)))
  elif type(i[-1])== type(""): 
    print(round(c_degrees(F)))   
  """
  Es extraño explicar este ultimo paso de elif, pero lo que se quiere decir es
  que independientemente de cualquier cosa, solo se quiere llegar a que
  imprima una vez el resultado para el caso de F sea dado como int, 
  Nota: me tomo más de lo que pensaba
  """